name: Runway

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/runway.py'
      - 'finance/**'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  runway:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4

      - name: Ensure input file present
        id: input
        run: |
          if [ ! -f finance/input/transactions.csv ]; then
            echo "no_input=true" >> $GITHUB_OUTPUT
          fi

      - name: Set savings (default 0)
        id: savings
        run: echo "value=${{ github.event.inputs.savings || '0' }}" >> $GITHUB_OUTPUT

      - name: Setup Python
        if: steps.input.outputs.no_input != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run runway script
        if: steps.input.outputs.no_input != 'true'
        run: |
          python scripts/runway.py "${{ steps.savings.outputs.value }}" | tee runway.log
          echo "REPORT_PATH=finance/runway_report.md" >> $GITHUB_ENV

      - name: Upload report artifact
        if: steps.input.outputs.no_input != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: runway-report
          path: finance/runway_report.md

      - name: Comment summary on PR
        if: steps.input.outputs.no_input != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const text = fs.readFileSync('runway.log','utf8');
            const m = text.match(/SUMMARY::avg_burn=([0-9.]+);runway_months=([0-9.]+)/);
            const summary = m ? `**Runway Report**\n\n- Avg monthly burn: **$${Number(m[1]).toFixed(2)}**\n- Estimated runway: **${Number(m[2]).toFixed(1)} months**\n\nFull report generated: \`finance/runway_report.md\` (also attached as artifact).` : "Runway report generated.";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: summary
            });

      - name: On merge, commit report to reports/
        if: github.event_name == 'pull_request' && steps.input.outputs.no_input != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            if (context.payload.pull_request.merged) {
              const fs = require('fs');
              const path = `finance/reports/${new Date().toISOString().slice(0,10)}-runway.md`;
              fs.mkdirSync('finance/reports', { recursive: true });
              fs.copyFileSync('finance/runway_report.md', path);
              await exec.exec('git', ['config','user.name','github-actions']);
              await exec.exec('git', ['config','user.email','github-actions@github.com']);
              await exec.exec('git', ['add', path]);
              await exec.exec('git', ['commit','-m',`chore: archive runway report ${path}`]);
              await exec.exec('git', ['push']);
            }